# Generated by Django 2.2.6 on 2019-10-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Subscriber',
        ),
    ]
